### ISSUE TITLE
ACME v2 support

### ISSUE THREAD

**Issue by piraz** [candango/automatoes#4]
Implement https://github.com/veeti/manuale/issues/40 as requested in manuale.

To accomplish this ticket we need to implement:

- [x] #7 ACME V2 get nounce[RFC Section 7.2](https://tools.ietf.org/html/rfc8555#section-7.2)
- [x] #5 ACME V2 Account Registration [RFC Section 7.3](https://tools.ietf.org/html/rfc8555#section-7.3)
- [x] #16 ACME V2 Account Info [RFC Section  7.3](https://tools.ietf.org/html/rfc8555#section-7.3)
- [x] #18 ACME V2 Applying for Certificate Issuance [RFC Section  7.4](https://tools.ietf.org/html/rfc8555#section-7.4)
- [x] #20  ACME V2 Download Certificate [RFC Section  7.4.2](https://tools.ietf.org/html/rfc8555#section-7.4.2)
- [x] #25 ACME V2 Certificate Revocation [RFC Section  7.6](https://tools.ietf.org/html/rfc8555#section-7.6)
- [x] #10 [Create mock server to test challenges](https://github.com/candango/automatoes/issues/10)

**Comment by piraz** [comment]
This is priority. End Of Life is near: https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

**Comment by piraz** [comment]
Here is the spec: https://tools.ietf.org/html/draft-ietf-acme-acme-09

**Comment by cpu** [comment]
> Here is the spec: https://tools.ietf.org/html/draft-ietf-acme-acme-09

:wave: Hi @piraz,

That's an early pre-RFC draft. You will want to refer to https://tools.ietf.org/html/rfc8555 instead of draft-ietf-acme-acme-09 or you'll run into problems (e.g. [not supporting POST-as-GET](https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380))

**Comment by piraz** [comment]
Using @cpu's reference, thanks.

**Comment by szepeviktor** [comment]
@piraz Do you plan to implement V2?

**Comment by piraz** [comment]
I'm implementing V2. Just got a new born this October and got me focused in another project.

Let's see if I can get things faster November.

**Comment by piraz** [comment]
Got the registration going. Seems pretty straight forward, I'll get the test finished and post the code.

We can keep using the same key format but I need to check the status of an V1 account in a V2 server.

**Comment by piraz** [comment]
> > Here is the spec: https://tools.ietf.org/html/draft-ietf-acme-acme-09
> 
>  Hi @piraz,
> 
> That's an early pre-RFC draft. You will want to refer to https://tools.ietf.org/html/rfc8555 instead of draft-ietf-acme-acme-09 or you'll run into problems (e.g. [not supporting POST-as-GET](https://community.letsencrypt.org/t/acme-v2-scheduled-deprecation-of-unauthenticated-resource-gets/74380))

Just a heads up @cpu, the url at https://tools.ietf.org/html/rfc8555#section-7.3 isn't correct. The right value is https://example.com/acme/new-acct.

**Comment by cpu** [comment]
> the url at https://tools.ietf.org/html/rfc8555#section-7.3 isn't correct. The right value is https://example.com/acme/new-acct.

@piraz You're correct that Boulder/Let's Encrypt use the path `/acme/new-acct` but that doesn't mean the examples in the RFC are incorrect. It consistently uses `/acme/new-account` throughout. 

Put another way: The individual URLs for each endpoint are customizable by the ACME server, you have to learn the correct value for each server using the `/directory` endpoint. In this case by checking the value of the "newAccount" key.

**Comment by szepeviktor** [comment]
Yes!

https://acme-v02.api.letsencrypt.org/directory

**Comment by piraz** [comment]
> ue of the `"newAccount"` key.

WOW. That's good info. Thanks @cpu I'll put that in the logic.

**Comment by cpu** [comment]
@piraz As you're working on ACME v2 support you might find it handy to test with both Let's Encrypt's staging environment and [Pebble](https://github.com/letsencrypt/pebble), a small ACME test server we made for this usage.

As one example Pebble deliberately chooses different paths for things like `newAccount` so if your client works with both Let's Encrypt staging (powered by Boulder) and Pebble you're likely to have done the right thing :-) That should help make `automatoes` work with other RFC 8555 CAs ([like Sectigo](https://sectigo.com/resources/sectigos-acme-automation))

**Comment by piraz** [comment]
Running Peeble automated @szepeviktor.

**Comment by piraz** [comment]
Just finished account registration and info, also added to the manuale command.

I'm breaking up Account Management into specific tasks as Account Registration and Account Info.

The agreement during V1 was done in 2 steps, on v2 we retrieve the term from the directory meta and send the agreement status during the registration, that will be changed in the logic also.

**Comment by piraz** [comment]
The good news @szepeviktor is that I got the full authorization and certificate download almost done.

What we should figure out right here, and suggestions are appreciated, how to adapt our workflow to ACME V2 workflow.

Before we used to do:

- Ask authorization for domain(s)
- Fulfill challenges
- Create keys for domain(s)

The csr used to be created in the step 3 with ACME V1.

ACME V2 is more order oriented. Here is what happens:

 - We ask authorization for domain(s), order is created
 - We fulfill challenges in the order
 - We finish the order, here we provide the csr
 - We check if the order status to be valid
 - We get access to the order certificate url
 - We download the certificate

So we can, with manuale, do everything in one step and/or break those steps and be more order oriented.

I can list all orders from an account, so what I can do things like:

- Block user from start an order from a combination of domains
- List pending orders
- Create a direct workflow
- Create a step-oriented workflow
- Create files or pipe order objects so we can process later

Do you have any input?

**Comment by piraz** [comment]
Another good news is that the account file generated by the ACME V1 manuale account will be the same.

**Comment by szepeviktor** [comment]
Thank you very much!
Does it mean that all features of the veeti's tool are still available?

**Comment by piraz** [comment]
Yes all features would be available and we can also create wildcard domains right now(Because we're on ACME 2).

I can try to do:
```
manuale authorize my.domain.com another.domain.com
manuale issue mydomain.com
manuale issue another.domain.com
```

I don't think this is possible right now because authorize creates one order and the issue must have both domains provided by authorize. I'm checking https://tools.ietf.org/html/rfc8555#section-7.5 to see if I can solve the example above.

This will work for sure:

```
manuale authorize my.domain.com another.domain.com
manuale issue my.domain.com another.domain.com
```
Because we create an order and issue will download the certificate from that order.

That works also:
```
manuale authorize my.domain.com
manuale issue my.domain.com
manuale authorize another.domain.com
manuale issue another.domain.com
```  
In this case we have two orders and two downloads.

I'm thinking about this:

```
manuale authorize my.domain.com another.domain.com
--- resolve the challenges --
response : order fdj394k4kf created

manuale list
response: orders created:
- rejk93kk3j foo.domain.com
- fdj394k4kf my.domain.com another.domain.com

manuale issue fdj394k4kf
```

That will be more order oriented bur will confuse manuale users.

I could keep manuale the way it is but issuing certs matching domains informed in the authorize command.

I can implement automatoes order oriented like this:

```
automatoes order create my.domain.com another.domain.com

automatoes order list
- rejk93kk3j foo.domain.com ready
- fdj394k4kf my.domain.com another.domain.com pending

automatoes order list
- rejk93kk3j foo.domain.com ready
- fdj394k4kf my.domain.com another.domain.com ready

automatoes order download fdj394k4kf
downloads cert to the local disk
```

**Comment by piraz** [comment]
Do you have any problems with those outputs for authorization?

Example 1:

```
manuale --server=https://acme-staging-v02.api.letsencrypt.org authorize monster.candango.org monster1.candango.org
Candango Automatoes 0.9.0. Manuale replacement.


Authorizing monster.candango.org, monster1.candango.org.

  Found order at ~/autotests/orders/order_monster.candango.org_monster1.candango.org.json. Querying ACME server for current status.
  Order still valid and expires at 2020-01-07T16:18:52Z.

  Requesting challenge for monster.candango.org.
    monster.candango.org is already authorized until 2020-02-06T09:15:55Z.
  Requesting challenge for monster1.candango.org.

  DNS verification required. Make sure these TXT records are in place:

    _acme-challenge.monster1.candango.org.  IN TXT  "4UnuRHePcrqM_cnEjJLzdNwOfoHWc4QoL4eHbMmHdkg"

Press Enter to continue.
```

Invalid order:

```
manuale --server=https://acme-staging-v02.api.letsencrypt.org authorize monster.candango.org monster1.candango.org
Candango Automatoes 0.9.0. Manuale replacement.


Authorizing monster.candango.org, monster1.candango.org.

  Found order at ~/autotests/orders/order_monster.candango.org_monster1.candango.org.json. Querying ACME server for current status.
  Invalid order. Renewing order.
  Just continue with the authorization when all verifications are in place.

  Requesting challenge for monster.candango.org.
    monster.candango.org is already authorized until 2020-02-06T09:15:55Z.
  Requesting challenge for monster1.candango.org.

  DNS verification required. Make sure these TXT records are in place:

    _acme-challenge.monster1.candango.org.  IN TXT  "v15O5YPC_bluMPpXKBHJ1_Qy568yEVCcs1HYDyodm_I"

Press Enter to continue.
```

I'll shrink the order file and add the challenges to the current directory. So you will have metadatas for your dns challenges in the disk before you press continue.

**Comment by piraz** [comment]
So when you authorize the first time the order file is created at current_dir/orders/domains.json.

If you fulfill all the challenges we set the order as ready and we close during the issue command, the issue command must contain all domains from the authorize with the right sequence of domains otherwise I will not be able to find the order and issue the certificate.

 If you press crt+c and break the authorize process and try to authorize the same domains in the same sequence I'll just query the order file from the disk and check if it is not expired and not invalid, and you can fulfill the challenges.

If you fail one challenge the order will be set as invalid, next time I need to create a new one(renew), and the domains authorized in the previous failed order will be keep authorized for you.

If the order is expired I create a new one(renew).

This is the behavior I got in staging(https://acme-staging-v02.api.letsencrypt.org ).

**Comment by szepeviktor** [comment]
> Do you have any problems with those outputs for authorization? @szepeviktor

No they are fine.

I've made my [DNS scripts](https://github.com/szepeviktor/debian-server-tools/blob/master/monitoring/aws-route53-rrs.sh#L75-L79) to accept 

```
     _acme-challenge.monster1.candango.org.  IN TXT  "v15O5YPC_bluMPpXKBHJ1_Qy568yEVCcs1HYDyodm_I"
```

**Comment by piraz** [comment]
Hey @cpu what about this https://tools.ietf.org/html/rfc8555#section-7.1.2.1?

It seems the object is not being returned by staging when I perform https://tools.ietf.org/html/rfc8555#section-7.1.2.

The orders object is not in the response from the account uri either by post or post_as_get.

Is that something that is not implemented yet?

**Comment by cpu** [comment]
> Is that something that is not implemented yet?

@piraz Yup, it's one of the features listed as not implemented on our [ACME divergences page](https://github.com/letsencrypt/boulder/blob/master/docs/acme-divergences.md#boulder-divergences-from-acme). There's a Boulder issue to subscribe to if you're interested: https://github.com/letsencrypt/boulder/issues/3335 It isn't likely to be something we prioritize anytime soon unfortunately.

If you wanted to test your code with an RFC 8555 server that does implement Section 7.1.2.1 and the orders endpoint we recently implemented it in [Pebble v2.3.0](https://github.com/letsencrypt/pebble/releases/tag/v2.3.0).

Hope that helps, happy new year :-)

**Comment by piraz** [comment]
Alright @cpu I'll see how to track that in the client side by now, sill working at the ACME v2 tool.

Thank you very much for all the support. Happy new year for you.

**Comment by piraz** [comment]
We're done for 0.9.1. Release this weekend.

Sorry for the delay @szepeviktor.

**Comment by piraz** [comment]
Tested package from pypi and it worked fine in production.

`pip install automatoes`

The virtualenv you're running should not have manuale installed. You must remove manuale before if it is the case.

Need to re-register my account but I think that updating the url to "https://acme-v02.api.letsencrypt.org/acme/acct/<account_id>" it works. Still need to test.

The information in the readme is not correct. Maybe we need a convert function if is possible.

**Comment by piraz** [comment]
The first domain certified by automates was https://trac.projenv.com.

**Comment by piraz** [comment]
.Release 0.9.0 published at https://pypi.org/project/automatoes.

**Comment by piraz** [comment]
Hey @szepeviktor, I just opened a bug to fix an existent account #30.

There is a workaround there so you can get your previous account working on Let's encrypt production server.

**Comment by szepeviktor** [comment]
Thank you.
