### ISSUE TITLE
Support Buypass GO ACME V2 protocol

### ISSUE THREAD

**Issue by szepeviktor** [candango/automatoes#67]
https://community.buypass.com/t/k9r5cx/get-started
What does it take to support Buypass? They also speak ACME/RFC 8555.

---

There is also ZeroSSL.com

**Comment by piraz** [comment]
Try to use --server. That will be good to see how smooth that will be with another sever supporting ACME/RFC 8555.

**Comment by piraz** [comment]
Do they have a test environment?

**Comment by szepeviktor** [comment]
Yes, `https://api.test4.buypass.no/acme/directory`
https://community.buypass.com/t/63d4ay/buypass-go-ssl-endpoints-updated-14-05-2020

**Comment by szepeviktor** [comment]
@piraz This is what I've got.
Please consider introducing HTTP level debug output. Thanks!

```
manuale --verbose --server https://api.test4.buypass.no/acme/directory register viktor@szepe.net
Candango Automatoes 0.9.5. Manuale replacement.


You're about to register a new account with e-mail viktor@szepe.net as contact. Continue? [Y/n] y
Generating a new account key. This might take a second.
  Key generated.
Registering...
  Retrieving terms of agreement ...
  This server requires you to agree to these terms:
    None
Agreed? [Y/n]
Oops! An unhandled error occurred. Please file a bug.
'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/opt/automatoes/lib/python3.7/site-packages/automatoes/cli.py", line 348, in manuale_main
    args.func(args)
  File "/opt/automatoes/lib/python3.7/site-packages/automatoes/cli.py", line 125, in _register
    key_file=args.key_file
  File "/opt/automatoes/lib/python3.7/site-packages/automatoes/register.py", line 78, in register
    acmev2.register(email, terms_agreed)
  File "/opt/automatoes/lib/python3.7/site-packages/automatoes/acme.py", line 330, in register
    payload
  File "/opt/automatoes/lib/python3.7/site-packages/automatoes/acme.py", line 507, in post
    protected = self.get_headers(url=self.path(path))
  File "/opt/automatoes/lib/python3.7/site-packages/automatoes/acme.py", line 227, in path
    if path.startswith("http"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

slightly different from https://acme-v02.api.letsencrypt.org/directory and from https://tools.ietf.org/html/rfc8555#section-7.1.1

![kép](https://user-images.githubusercontent.com/952007/99799328-c184d800-2b32-11eb-8faf-6858d5930ad1.png)

**Comment by szepeviktor** [comment]
I've called and emailed Buypass to find their v2 API endpoint.

**Comment by szepeviktor** [comment]
@piraz It turns out that `directory` endpoint lists both v1 and v2 endpoints!

1. https://tools.ietf.org/html/rfc8555#section-7.1.1
1. https://api.buypass.com/acme/directory
1. https://acme-v02.api.letsencrypt.org/directory

See?

Now it's time to find out the cause of the above error!

> 'NoneType' object has no attribute 'startswith'

**Comment by szepeviktor** [comment]
💥 Endpoint URL-s are hard-wired in our code!

```
$ grep -En 'self\.(get|post).*/acme' automatoes/acme.py
84:        response = self.post("/acme/new-reg", {
134:        response = self.post('/acme/new-authz', {
168:        response = self.post('/acme/new-cert', {
186:        response = self.post('/acme/revoke-cert', {
```

Please read those from the `/directory` response (`url_from_directory()`)
Thank you.

**Comment by piraz** [comment]
Are you using v2 right?

Your grep gets parts from v1. I'm overwriting them on v2 and using the the ones returned by directory.

Look for self.url_from_directory.

**Comment by szepeviktor** [comment]
> Are you using v2 right?

Could automatoes be mislead by having both v1 and v2 endpoints in https://api.buypass.com/acme/directory ?

**Comment by szepeviktor** [comment]
@piraz It turns out `urllib.parse.urljoin` truncates `--server https://api.test4.buypass.no/acme`
so `https://api.test4.buypass.no/directory` gets queried!

**Comment by szepeviktor** [comment]
What is the Python function that does this? https://github.com/candango/automatoes/pull/70/files

**Comment by piraz** [comment]
The problem here is that they don't implement the terms here:

https://github.com/candango/automatoes/blob/develop/automatoes/acme.py#L303-L309

They return 404 and we get return none.

After that we just drop the ball.

So the issue here is I need to go to the server, if 200 than I declare that you need to agree with tos, if not I just say no tos go ahead an don't bother by the tos.

I need to fix the logic here:

https://github.com/candango/automatoes/blob/develop/automatoes/register.py#L65-L79

Raising to a bug and moving to the next 0.9.6.

**Comment by szepeviktor** [comment]
> They return 404 and we get return none.

No, it is a directory URL issue:
`https://api.test4.buypass.no/directory` vs. https://api.test4.buypass.no/acme/directory
404 vs. 200

**Comment by piraz** [comment]
To fix this we need:

- [x] Fix url handling when acme is served with paths #71
- [x] Set expiration date to the order if server wont do it #72
- [x] Show only information provided by the server with manuale info #73

**Comment by piraz** [comment]
Should work with 0.9.6.

**Comment by szepeviktor** [comment]
Thank you.
Could you [tag](https://github.com/candango/automatoes/tags) this new release?

**Comment by piraz** [comment]
On pypi and here https://github.com/candango/automatoes/releases/tag/v0.9.6/

**Comment by szepeviktor** [comment]
:)

```
$ env/bin/manuale --server https://api.test4.buypass.no/acme issue szepe.net

/home/viktor/src/RandomOpenSource/automatoes/env/lib/python3.5/site-packages/automatoes-0.9.6-py3.5.egg/automatoes/crypto.py:26: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
Candango Automatoes 0.9.6. Manuale replacement.


Generating a 4096 bit RSA key. This might take a second.
  Key generated.
  Order updated with generated key.
Requesting certificate issuance...
  We already know the certificate uri for order 6c87b61c9188d269d4afb6ffe568f4907948b0de8837009d0e732e29a8c5e43a. Downloading certificate.
  Certificate downloaded.
  Expires: 2021-05-25
   SHA256: fd171aaab9dba54ddc8aad0ca85d35ae4c4759c41fd5f87dc63e71bd8da562a0

  Wrote key to /home/viktor/src/RandomOpenSource/automatoes/szepe.net.pem
  Wrote certificate to /home/viktor/src/RandomOpenSource/automatoes/szepe.net.crt
  Wrote certificate with intermediate to /home/viktor/src/RandomOpenSource/automatoes/szepe.net.chain.crt
  Wrote intermediate certificate to /home/viktor/src/RandomOpenSource/automatoes/szepe.net.intermediate.crt
```

@bergelf

**Comment by piraz** [comment]
Nice!
